# Generated by Django 3.0 on 2021-12-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20211217_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='label',
            field=models.IntegerField(default=0),
        ),
    ]
