# Generated by Django 3.0 on 2021-12-17 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0004_auto_20211217_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmm.Label')),
            ],
        ),
    ]
